# Generated by Django 5.1.6 on 2025-03-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0003_categorie_fournisseur_produitnc_remove_produit_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='type',
            field=models.CharField(choices=[('em', 'Électroménager'), ('cs', 'Consommable'), ('fr', 'Frais'), ('mb', 'Meuble')], default='cs', max_length=2),
        ),
    ]
