# Generated by Django 5.1.6 on 2025-04-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0005_produit_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='prenom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
